name: Build

on: [ push ]

jobs:
  Build:
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/stable_')
    steps:
      - uses: actions/checkout@v3

      - name: Meta info
        id: meta
        run: |
          AWG_VERSION="$(printf "${{ github.ref_name }}" | cut -d_ -f2)"
          AWG_TOOLS_VERSION="$(printf "${{ github.ref_name }}" | cut -d_ -f3)"
          ACTOR="${{ github.actor }}"
          REPO="${{ github.event.repository.name }}"

          echo "awg_version=$AWG_VERSION" >> $GITHUB_OUTPUT
          echo "awg_tools_version=$AWG_TOOLS_VERSION" >> $GITHUB_OUTPUT
          echo "tag_name=$(tr '[:upper:]' '[:lower:]' <<< "${ACTOR}/${REPO}")" >> $GITHUB_OUTPUT
          echo "tag_version=${AWG_VERSION}_${AWG_TOOLS_VERSION}" >> $GITHUB_OUTPUT

      - name: Login to Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./Dockerfile
          push: true
          platforms: linux/amd64,linux/arm64,linux/arm/v7
          build-args: |
            "AWG_VERSION=${{ steps.meta.outputs.awg_version }}"
            "AWG_TOOLS_VERSION=${{ steps.meta.outputs.awg_tools_version }}"
          tags: |
            ghcr.io/${{ steps.meta.outputs.tag_name }}:${{ steps.meta.outputs.tag_version }}
            ghcr.io/${{ steps.meta.outputs.tag_name }}:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max

  Build-Nightly:
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/nightly_')
    steps:
      - uses: actions/checkout@v3

      - name: Meta info
        id: meta
        run: |
          AWG_VERSION="$(printf "${{ github.ref_name }}" | cut -d_ -f2)"
          AWG_TOOLS_VERSION="$(printf "${{ github.ref_name }}" | cut -d_ -f3)"
          ACTOR="${{ github.actor }}"
          REPO="${{ github.event.repository.name }}"

          echo "awg_version=$AWG_VERSION" >> $GITHUB_OUTPUT
          echo "awg_tools_version=$AWG_TOOLS_VERSION" >> $GITHUB_OUTPUT
          echo "tag_name=$(tr '[:upper:]' '[:lower:]' <<< "${ACTOR}/${REPO}")" >> $GITHUB_OUTPUT
          echo "tag_version=${AWG_VERSION}_${AWG_TOOLS_VERSION}" >> $GITHUB_OUTPUT

      - name: Login to Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./Dockerfile-nightly
          push: true
          platforms: linux/amd64,linux/arm64,linux/arm/v7
          tags: |
            ghcr.io/${{ steps.meta.outputs.tag_name }}:nightly_${{ steps.meta.outputs.tag_version }}
            ghcr.io/${{ steps.meta.outputs.tag_name }}:nightly_latest
          cache-from: type=gha
          cache-to: type=gha,mode=max
